# Generated by Django 3.1.2 on 2021-03-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('lastdegree', models.CharField(max_length=50)),
                ('degreename', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=200)),
                ('dateofjoining', models.DateField()),
                ('dateofEnding', models.DateField()),
                ('favsport', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('shortBio', models.TextField()),
            ],
        ),
    ]
