# Generated by Django 3.1.2 on 2021-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='dateofEnding',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='dateofjoining',
            field=models.DateField(blank=True),
        ),
    ]
