# Generated by Django 3.1.2 on 2021-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_site', '0002_auto_20210304_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='dateofEnding',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='dateofjoining',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
